### ISSUE TITLE
File .Exe doesn't work

### ISSUE THREAD

**Issue by Tharcisio48** [Carsmaniac/paintjob-packer#3]
I downloaded the file, but it doesn't work. I click on it several times, and nothing happens. I have already disabled the antivirus and even so, the file does not work. What should I do?

**Comment by Carsmaniac** [comment]
I'm not sure why that would be happening. You could try downloading the source code, and then running `packer.py` directly, you'll need [Python 3](https://www.python.org/downloads/).

There seem to be a few issues with the .exe, I might look into making it in some other way, so that it works more reliably. Thanks for reporting your issue :)
